LPS-135809 Fix test ViewIdPSingleLogoutWithMultipleSPs
gaborlovasdotcom/liferay-portal pull request #117
Opened 2021-07-20 09:52 UTC by weller0246

https://issues.liferay.com/browse/LPS-135809

2021-07-20 09:52 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-20 09:52 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-20 09:53 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-20 09:53 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-20 09:53 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-20 09:53 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-20 09:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/394/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/394/jenkins-report.html">here</a>.</b></p>

2021-07-20 09:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3078/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3078/jenkins-report.html">here</a>.</b></p>

2021-07-20 11:53 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 7 out of 9 jobs passed in 1 hour 60 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2123">Acceptance Upstream DXP (master) #2123</a></p><details><summary><strong>ci:test:saml - 7 out of 9 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3078/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331787/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>7 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363665/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22586/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331786/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3494/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/419138/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3495/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3496/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3078/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331787/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>7 Tests Passed.<br/>15 Tests Failed.</p></div><ol><li><div><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/331787//consoleText">AXIS_VARIABLE=0,label_exp=!master #331787</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-10-190] which is computer hudson.slaves.SlaveComputer@30a1ee7e and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute Scripts' marked build as failure
Finished: FAILURE</code></pre></div></li><li><div><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/331787//consoleText">AXIS_VARIABLE=12,label_exp=!master #331787</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-10-159] which is computer hudson.slaves.SlaveComputer@40cb976f and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.pe [...]

2021-07-20 12:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3078/">test-portal-acceptance-pullrequest(master)#3078</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3078/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/117">gaborlovasdotcom#117</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548389903">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#117 - 2021-07-20[02:53:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8660/">publish-testray-report#8660</a><br/></div></div>

2021-07-20 15:47 UTC, gaborlovasdotcom commented
ci:test:saml:nocompile

2021-07-20 15:47 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-20 15:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/404/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/404/jenkins-report.html">here</a>.</b></p>

2021-07-20 16:46 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 1 out of 3 jobs passed in 59 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2123">Acceptance Upstream DXP (master) #2123</a></p><details><summary><strong>ci:test:saml - 1 out of 3 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/404/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22720/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3627/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li></ul></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/404/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22720/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>47 Tests Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/22720//consoleText">AXIS_VARIABLE=5,label_exp=!master #22720</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/22720//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout_">LocalFile.SAML#AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/404/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/404/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/404/functional-tomcat90-mysql57-jdk8/0/5/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/22720//consoleText">AXIS_VARIABLE=6,label_exp=!master #22720</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/22720//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExistsAfterSPSessionTimeout_">LocalFile.SAML#AssertSSOSessionExistsAfterSPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/404/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/404/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/404/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/22720//consoleText">AXIS_VARIABLE=7,label_exp=!master #22720</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/22720//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExpiresAfterMaximumSessionAge_">LocalFile.SAML#AssertSSOSessionExpiresAfterMaximumSessionAge</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/404/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/404/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/404/functional-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-07-20 16:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/404/">test-portal-acceptance-pullrequest(master)#404</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/404/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/117">gaborlovasdotcom#117</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548459464">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#117 - 2021-07-20[08:47:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/492/">publish-testray-report#492</a><br/></div></div>

2021-07-20 16:53 UTC, gaborlovasdotcom commented
ci:test:saml:nocompile

2021-07-20 16:53 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-20 16:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/408/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/408/jenkins-report.html">here</a>.</b></p>

2021-07-20 17:33 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 0 out of 2 jobs passed in 39 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0ea7cfcee785f4a642b944b15937de099275b013">0ea7cfcee785f4a642b944b15937de099275b013</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2123">Acceptance Upstream DXP (master) #2123</a></p><details><summary><strong>ci:test:saml - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/408/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22748/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/408/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22748/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/22748//consoleText">AXIS_VARIABLE=0,label_exp=!master #22748</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/22748//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewIdPSingleLogoutWithMultipleSPs_">LocalFile.SAML#ViewIdPSingleLogoutWithMultipleSPs</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/408/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SAML_ViewIdPSingleLogoutWithMultipleSPs/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/408/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SAML_ViewIdPSingleLogoutWithMultipleSPs/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/408/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-07-20 17:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/408/">test-portal-acceptance-pullrequest(master)#408</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/408/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/117">gaborlovasdotcom#117</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548477327">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#117 - 2021-07-20[09:53:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/498/">publish-testray-report#498</a><br/></div></div>

2021-07-20 18:06 UTC, gaborlovasdotcom requested changes
Please fix the test, test out locally, and update the successful test result to the ticket.

2021-07-20 18:06 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +			userEmailAddress = "test@www.able.com",
@weller0246, According to the test's original design, at this point, what will be the Instance admin's email address?

2021-07-20 18:06 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +			userEmailAddress = "test@www.baker.com",
@weller0246, According to the test's original design, at this point, what will be the Instance admin's email address?

2021-07-20 18:06 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> -		// Initiate Single Logout for IdP
@weller0246, Please leave the comments which help the test's readability.

2021-07-20 18:06 UTC, gaborlovasdotcom commented on test.properties
> +        (portal.upstream == "marci") AND \
Shall be removed before forwarding.

2021-07-20 18:06 UTC, gaborlovasdotcom commented on test.properties
> +        functional-tomcat90-mysql57-jdk8
Shall be removed before forwarding.

2021-07-21 13:22 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-21 13:22 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-21 13:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3136/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3136/jenkins-report.html">here</a>.</b></p>

2021-07-21 13:28 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-21 13:28 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-21 13:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/76/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/76/jenkins-report.html">here</a>.</b></p>

2021-07-21 13:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 0 out of 1 jobs passed in 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39b2dd1effe8f6ca32ef1e233a584339d8a3922b">39b2dd1effe8f6ca32ef1e233a584339d8a3922b</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39b2dd1effe8f6ca32ef1e233a584339d8a3922b">39b2dd1effe8f6ca32ef1e233a584339d8a3922b</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2128">Acceptance Upstream DXP (master) #2128</a></p><details><summary><strong>ci:test:saml - 0 out of 1 jobs PASSED</strong></summary></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3136/jenkins-report.html">here</a>.</h5></details></html>

2021-07-21 13:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3136/">test-portal-acceptance-pullrequest(master)#3136</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3136/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/117">gaborlovasdotcom#117</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8787/">publish-testray-report#8787</a><br/></div></div>

2021-07-21 14:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:saml - 2 out of 2 jobs passed in 44 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39b2dd1effe8f6ca32ef1e233a584339d8a3922b">39b2dd1effe8f6ca32ef1e233a584339d8a3922b</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39b2dd1effe8f6ca32ef1e233a584339d8a3922b">39b2dd1effe8f6ca32ef1e233a584339d8a3922b</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2128">Acceptance Upstream DXP (master) #2128</a></p><details><summary><strong>ci:test:saml - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/76/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/770/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/76/jenkins-report.html">here</a>.</h5></details></html>

2021-07-21 14:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/76/">test-portal-acceptance-pullrequest(master)#76</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/76/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/117">gaborlovasdotcom#117</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548664297">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#117 - 2021-07-21[06:29:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/198/">publish-testray-report#198</a><br/></div></div>

2021-07-22 07:23 UTC, gaborlovasdotcom commented
ci:test:saml:nocompile

2021-07-22 07:24 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-22 07:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/9841/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9841/jenkins-report.html">here</a>.</b></p>

2021-07-22 07:39 UTC, ferenconodiD approved these changes
LGTM!

2021-07-22 09:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 7 out of 9 jobs passed in 1 hour 44 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cc8a98c4ae038d3068c6d467d27d9c8e4adb2e38">cc8a98c4ae038d3068c6d467d27d9c8e4adb2e38</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cc8a98c4ae038d3068c6d467d27d9c8e4adb2e38">cc8a98c4ae038d3068c6d467d27d9c8e4adb2e38</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2133">Acceptance Upstream DXP (master) #2133</a></p><details><summary><strong>ci:test:saml - 7 out of 9 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/9841/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23273/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>7 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23270/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23271/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23272/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23269/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363855/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363854/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363856/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9841/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23273/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>47 Tests Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/23273//consoleText">AXIS_VARIABLE=5,label_exp=!master #23273</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/23273//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout_">LocalFile.SAML#AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-3/test-portal-acceptance-pullrequest(master)/9841/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-3/test-portal-acceptance-pullrequest(master)/9841/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-3/test-portal-acceptance-pullrequest(master)/9841/functional-tomcat90-mysql57-jdk8/0/5/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/23273//consoleText">AXIS_VARIABLE=6,label_exp=!master #23273</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/23273//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExistsAfterSPSessionTimeout_">LocalFile.SAML#AssertSSOSessionExistsAfterSPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-3/test-portal-acceptance-pullrequest(master)/9841/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-3/test-portal-acceptance-pullrequest(master)/9841/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-3/test-portal-acceptance-pullrequest(master)/9841/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/23273//consoleText">AXIS_VARIABLE=7,label_exp=!master #23273</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/23273//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExpiresAfterMaximumSessionAge_">LocalFile.SAML#AssertSSOSessionExpiresAfterMaximumSessionAge</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-3/test-portal-acceptance-pullrequest(master)/9841/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-3/test-portal-acceptance-pullrequest(master)/9841/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-3/test-portal-acceptance-pullrequest(master)/9841/functional-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-07-22 09:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/9841/">test-portal-acceptance-pullrequest(master)#9841</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9841/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/117">gaborlovasdotcom#117</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548805307">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#117 - 2021-07-22[00:27:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/1637/">publish-testray-report#1637</a><br/></div></div>

2021-07-22 09:16 UTC, gaborlovasdotcom requested changes

2021-07-22 09:16 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +		MyAccount.openMyAccountAdmin(baseURL = "http://www.test.com:8080");
@weller0246 Could you please change this URL to http://localhost:8080, according to the test case terminolodgy.

2021-07-22 09:57 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-22 09:57 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-22 10:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3164/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3164/jenkins-report.html">here</a>.</b></p>

2021-07-22 13:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 7 out of 9 jobs passed in 3 hours 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5bd25d65e74ce19974cd5a7ff3443cb0f022b79">b5bd25d65e74ce19974cd5a7ff3443cb0f022b79</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5bd25d65e74ce19974cd5a7ff3443cb0f022b79">b5bd25d65e74ce19974cd5a7ff3443cb0f022b79</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2134">Acceptance Upstream DXP (master) #2134</a></p><details><summary><strong>ci:test:saml - 7 out of 9 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3164/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467287/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>7 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4172/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4171/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/439712/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/342195/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15193/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/501960/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/474111/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3164/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467287/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>13 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=9,label_exp=!master/467287//consoleText">AXIS_VARIABLE=9,label_exp=!master #467287</a><pre><code>Build was aborted</code></pre></div></li><li><div><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=15,label_exp=!master/467287//consoleText">AXIS_VARIABLE=15,label_exp=!master #467287</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-110-20] which is computer hudson.slaves.SlaveComputer@623c7aab and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute Scripts' marked build as failure
Finished: FAILURE</code></pre></div></li><li><div><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/467287//consoleText">AXIS_VARIABLE=2,label_exp=!master #467287</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-110-19] which is computer hudson.slaves.SlaveComputer@763f4b59 and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Proce [...]

2021-07-22 13:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3164/">test-portal-acceptance-pullrequest(master)#3164</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3164/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/117">gaborlovasdotcom#117</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548870716">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#117 - 2021-07-22[03:02:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8882/">publish-testray-report#8882</a><br/></div></div>

2021-07-22 13:41 UTC, gaborlovasdotcom approved these changes

2021-07-22 13:42 UTC, gaborlovasdotcom commented
Test case [passed](https://testray.liferay.com/home/-/testray/case_results/1548870789?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1548870716%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) in test run

2021-07-22 13:42 UTC, gaborlovasdotcom commented
ci:forward

2021-07-22 13:42 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-07-22 13:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/5921/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-portal-source-format/builds/5921/jenkins-report.html">here</a>.</b></p>

2021-07-22 13:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5bd25d65e74ce19974cd5a7ff3443cb0f022b79">b5bd25d65e74ce19974cd5a7ff3443cb0f022b79</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/weller0246/liferay-portal/tree/LPS-135809">LPS-135809</a><br/>Branch GIT ID: <a href="https://github.com/weller0246/liferay-portal/commit/49215a1b4eb34eea087ad47e8eb2cc3a9637a2b2">49215a1b4eb34eea087ad47e8eb2cc3a9637a2b2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5921/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5921/jenkins-report.html">here</a>.</h5></details></html>

2021-07-22 13:47 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-19.liferay.com/job/test-portal-source-format/5921//consoleFull)

2021-07-22 13:47 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/104673
[Console](https://test-1-19.liferay.com/job/test-portal-source-format/5921//consoleFull)

2021-07-22 13:47 UTC, closed without merging

2021-07-22 13:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5921/">test-portal-source-format#5921</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5921/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/117">gaborlovasdotcom#117</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548871414">[master] ci:test:sf - weller0246 &gt; gaborlovasdotcom - PR#117 - 2021-07-22[06:43:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/1655/">publish-testray-report#1655</a><br/></div></div>

2021-07-22 13:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/4987/">test-portal-acceptance-pullrequest(master)#4987</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4987/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/117">gaborlovasdotcom#117</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548871423">[master] ci:test:relevant - weller0246 &gt; gaborlovasdotcom - PR#117 - 2021-07-22[06:43:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/1524/">publish-testray-report#1524</a><br/></div></div>