Test fix SAML#AssertSSOWithEncryptionAndDecryption
gaborlovasdotcom/liferay-portal pull request #128
Opened 2021-07-30 09:10 UTC by weller0246

https://issues.liferay.com/browse/LPS-136416

2021-07-30 09:10 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-30 09:10 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-30 09:10 UTC, weller0246 commented
ci:test:sf

2021-07-30 09:10 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-30 09:10 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-30 09:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3134/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/3134/jenkins-report.html">here</a>.</b></p>

2021-07-30 09:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/weller0246/liferay-portal/tree/LPS-136416">LPS-136416</a><br/>Branch GIT ID: <a href="https://github.com/weller0246/liferay-portal/commit/9978542b17f527f8218724049a4087b166f49688">9978542b17f527f8218724049a4087b166f49688</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3134/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3134/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/macros/SAML.macro expected:&lt;...er.firstLoginPG(
     [java] 			[userEmailAddress = "\$\{userEmailAddress\}",
     [java] 			virtualHostsURL = "\$\{virtualHostsURL\}");
     [java] 
     [java] 		ApplicationsMenu.gotoPortlet(
     [java] 			category = "Security",
     [java] 			panel = "Control Panel",
     [java] 			portlet = "SAML Admin");
     [java] 
     [java] 		SAMLRole.deleteCertificate();
     [java] 
     [java] 		User.logoutPG(specificURL = "\$\{virtualHostsURL\}");
     [java] 	\}
     [java] 
     [java] 	@description = "Enable encryption"
     [java] 	macro enableEncryptionOnSPConnection \{
     [java] 		if (isSet(userEmailAddress)) \{
     [java] 			User.firstLoginUI(
     [java] 				password = "test",
     [java] 				specificURL = "\$\{idpURL\}",
     [java] 				userEmailAddress = "\$\{userEmailAddress\}");
     [java] 		\}
     [java] 		else \{
     [java] 			User.firstLoginUI(
     [java] 				password = "test",
     [java] 				specificURL = "\$\{idpURL\}",
     [java] 				userEmailAddress = "test@liferay.com");
     [java] 		\}
     [java] 
     [java] 		ApplicationsMenu.gotoPortlet(
     [java] 			category = "Security",
     [java] 			panel = "Control Panel",
     [java] 			portlet = "SAML Admin");
     [java] 
     [java] 		SAMLNavigation.gotoServiceProviderConnection();
     [java] 
     [java] 		SAMLPortlet.configureServiceProviderConnection(
     [java] 			forceEncryption = "enable",
     [java] 		]	samlEntityID = "\$\{s...&gt; but was:&lt;...er.firstLoginPG(
     [java] 			[virtualHostsURL = "\$\{virtualHostsURL\}",
     [java] 			userEmailAddress = "\$\{userEmailAddress\}");
     [java] 
     [java] 		ApplicationsMenu.gotoPortlet(
     [java] 			category = "Security",
     [java] 			panel = "Control Panel",
     [java] 			portlet = "SAML Admin");
     [java] 
     [java] 		SAMLRole.deleteCertificate();
     [java] 
     [java] 		User.logoutPG(specificURL = "\$\{virtualHostsURL\}");
     [java] 	\}
     [java] 
     [java] 	@description = "Enable encryption"
     [java] 	macro enableEncryptionOnSPConnection \{
     [java] 		if (isSet(userEmailAddress)) \{
     [java] 			User.firstLoginUI(
     [java] 				password = "test",
     [java] 				specificURL = "\$\{idpURL\}",
     [java] 				userEmailAddress = "\$\{userEmailAddress\}");
     [java] 		\}
     [java] 		else \{
     [java] 			User.firstLoginUI(
     [java] 				password = "test",</code></pre></details></html>

2021-07-30 09:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3134/">test-portal-source-format#3134</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3134/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550555471">[master] ci:test:sf - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-07-30[02:11:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9534/">publish-testray-report#9534</a><br/></div></div>

2021-07-30 09:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3379/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3379/jenkins-report.html">here</a>.</b></p>

2021-07-30 09:55 UTC, weller0246 commented
ci:test:sf

2021-07-30 09:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/34/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-source-format/builds/34/jenkins-report.html">here</a>.</b></p>

2021-07-30 09:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/weller0246/liferay-portal/tree/LPS-136416">LPS-136416</a><br/>Branch GIT ID: <a href="https://github.com/weller0246/liferay-portal/commit/48dcf57824f6ee08515ce2a286bc900d24e2c667">48dcf57824f6ee08515ce2a286bc900d24e2c667</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/34/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/34/jenkins-report.html">here</a>.</h5></details></html>

2021-07-30 10:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/34/">test-portal-source-format#34</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/34/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550562935">[master] ci:test:sf - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-07-30[02:56:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/112/">publish-testray-report#112</a><br/></div></div>

2021-07-30 10:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 6 out of 9 jobs passed in 1 hour</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2167">Acceptance Upstream DXP (master) #2167</a></p><details><summary><strong>ci:test:saml - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3379/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6167/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/305/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/306/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/304/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2869/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6166/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/307/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3379/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>46 Tests Passed.<br/>4 Tests Failed.</p></div><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/460//consoleText">AXIS_VARIABLE=5,label_exp=!master #460</a><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/460//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout_">LocalFile.SAML#AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql57-jdk8/0/5/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/460//consoleText">AXIS_VARIABLE=6,label_exp=!master #460</a><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/460//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExistsAfterSPSessionTimeout_">LocalFile.SAML#AssertSSOSessionExistsAfterSPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/460//consoleText">AXIS_VARIABLE=7,label_exp=!master #460</a><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/460//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExpiresAfterMaximumSessionAge_">LocalFile.SAML#AssertSSOSessionExpiresAfterMaximumSessionAge</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/460//consoleText">AXIS_VARIABLE=8,label_exp=!master #460</a><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/460//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOWithEncryptionAndDecryption_">LocalFile.SAML#AssertSSOWithEncryptionAndDecryption</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql57-jdk8/0/8/LocalFile.SAML_AssertSSOWithEncryptionAndDecryption/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/3379/functional-tomcat90-mysql5 [...]

2021-07-30 10:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3379/">test-portal-acceptance-pullrequest(master)#3379</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3379/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550563536">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-07-30[02:11:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9535/">publish-testray-report#9535</a><br/></div></div>

2021-07-30 10:35 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-30 10:35 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-30 10:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/667/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/667/jenkins-report.html">here</a>.</b></p>

2021-07-30 11:30 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 6 out of 9 jobs passed in 54 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2167">Acceptance Upstream DXP (master) #2167</a></p><details><summary><strong>ci:test:saml - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/667/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6172/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/312/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/311/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6171/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/481/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/483/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2899/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/667/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6172/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>45 Tests Passed.<br/>5 Tests Failed.</p></div><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/6172//consoleText">AXIS_VARIABLE=5,label_exp=!master #6172</a><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/6172//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout_">LocalFile.SAML#AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-mysql57-jdk8/0/5/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/6172//consoleText">AXIS_VARIABLE=6,label_exp=!master #6172</a><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/6172//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExistsAfterSPSessionTimeout_">LocalFile.SAML#AssertSSOSessionExistsAfterSPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/6172//consoleText">AXIS_VARIABLE=7,label_exp=!master #6172</a><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/6172//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExpiresAfterMaximumSessionAge_">LocalFile.SAML#AssertSSOSessionExpiresAfterMaximumSessionAge</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/6172//consoleText">AXIS_VARIABLE=8,label_exp=!master #6172</a><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/6172//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOWithEncryptionAndDecryption_">LocalFile.SAML#AssertSSOWithEncryptionAndDecryption</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-mysql57-jdk8/0/8/LocalFile.SAML_AssertSSOWithEncryptionAndDecryption/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-27/test-portal-acceptance-pullrequest(master)/667/functional-tomcat90-my [...]

2021-07-30 11:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/667/">test-portal-acceptance-pullrequest(master)#667</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/667/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550617080">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-07-30[03:35:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/1300/">publish-testray-report#1300</a><br/></div></div>

2021-07-30 13:02 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-30 13:02 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-30 13:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/22/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/22/jenkins-report.html">here</a>.</b></p>

2021-07-30 13:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 6 out of 9 jobs passed in 55 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2167">Acceptance Upstream DXP (master) #2167</a></p><details><summary><strong>ci:test:saml - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/22/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6201/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2937/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6200/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6198/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6199/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/324/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2936/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/506/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/22/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6201/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>46 Tests Passed.<br/>4 Tests Failed.</p></div><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/6201//consoleText">AXIS_VARIABLE=5,label_exp=!master #6201</a><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/6201//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout_">LocalFile.SAML#AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-30/test-portal-acceptance-pullrequest(master)/22/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-30/test-portal-acceptance-pullrequest(master)/22/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-30/test-portal-acceptance-pullrequest(master)/22/functional-tomcat90-mysql57-jdk8/0/5/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/6201//consoleText">AXIS_VARIABLE=6,label_exp=!master #6201</a><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/6201//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExistsAfterSPSessionTimeout_">LocalFile.SAML#AssertSSOSessionExistsAfterSPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-30/test-portal-acceptance-pullrequest(master)/22/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-30/test-portal-acceptance-pullrequest(master)/22/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-30/test-portal-acceptance-pullrequest(master)/22/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/6201//consoleText">AXIS_VARIABLE=8,label_exp=!master #6201</a><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/6201//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOWithEncryptionAndDecryption_">LocalFile.SAML#AssertSSOWithEncryptionAndDecryption</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-30/test-portal-acceptance-pullrequest(master)/22/functional-tomcat90-mysql57-jdk8/0/8/LocalFile.SAML_AssertSSOWithEncryptionAndDecryption/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-30/test-portal-acceptance-pullrequest(master)/22/functional-tomcat90-mysql57-jdk8/0/8/LocalFile.SAML_AssertSSOWithEncryptionAndDecryption/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-30/test-portal-acceptance-pullrequest(master)/22/functional-tomcat90-mysql57-jdk8/0/8/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2937/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>25 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/2937//consoleText">AXIS_VARIABLE=1,label_exp=!master #2937</a><ol><li><div><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/2937//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewIdPSingleLogoutWithMultipleSPs_">LocalFile.SAML#ViewIdPSingleLogoutWithMultipleSPs</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-07/test-1-30/test-portal-acceptance-pullrequest(master)/22/functional-tomcat90-my [...]

2021-07-30 14:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/22/">test-portal-acceptance-pullrequest(master)#22</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/22/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550644062">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-07-30[06:03:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/69/">publish-testray-report#69</a><br/></div></div>

2021-07-30 14:44 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-30 14:44 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-30 14:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/44/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/44/jenkins-report.html">here</a>.</b></p>

2021-07-30 16:19 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 6 out of 9 jobs passed in 1 hour 36 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2167">Acceptance Upstream DXP (master) #2167</a></p><details><summary><strong>ci:test:saml - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/44/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440701/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/478128/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6215/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440699/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6213/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6216/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6214/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15551/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/44/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440701/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>10 Tests Passed.<br/>7 Tests Failed.</p></div><ol><li><div><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=19,label_exp=!master/440701//consoleText">AXIS_VARIABLE=19,label_exp=!master #440701</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-19-242] which is computer hudson.slaves.SlaveComputer@3a515528 and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute Scripts' marked build as failure
Finished: FAILURE</code></pre></div></li><li><div><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/440701//consoleText">AXIS_VARIABLE=2,label_exp=!master #440701</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-19-236] which is computer hudson.slaves.SlaveComputer@45786684 and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson. [...]

2021-07-30 16:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/44/">test-portal-acceptance-pullrequest(master)#44</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/44/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550699143">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-07-30[07:44:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/125/">publish-testray-report#125</a><br/></div></div>

2021-07-30 16:50 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-30 16:50 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-30 16:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/29/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/29/jenkins-report.html">here</a>.</b></p>

2021-07-30 17:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:saml - 8 out of 8 jobs passed in 53 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2167">Acceptance Upstream DXP (master) #2167</a></p><details><summary><strong>ci:test:saml - 8 out of 8 jobs PASSED</strong></summary><details><summary><strong>8 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/29/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25605/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25607/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25606/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/350/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/352/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/351/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25608/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/29/jenkins-report.html">here</a>.</h5></details></html>

2021-07-30 17:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/29/">test-portal-acceptance-pullrequest(master)#29</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/29/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550707240">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-07-30[09:50:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/91/">publish-testray-report#91</a><br/></div></div>

2021-08-02 07:27 UTC, weller0246 commented
ci:test:saml:nocompile

2021-08-02 07:27 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-08-02 07:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/8609/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8609/jenkins-report.html">here</a>.</b></p>

2021-08-02 09:28 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 6 out of 9 jobs passed in 1 hour 59 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2168">Acceptance Upstream DXP (master) #2168</a></p><details><summary><strong>ci:test:saml - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/8609/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440730/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/364295/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467673/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467675/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440035/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440036/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/364294/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467674/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8609/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440730/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>10 Tests Passed.<br/>5 Tests Failed.</p></div><ol><li><div><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/440730//consoleText">AXIS_VARIABLE=0,label_exp=!master #440730</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-19-222] which is computer hudson.slaves.SlaveComputer@1b1574ba and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute Scripts' marked build as failure
Finished: FAILURE</code></pre></div></li><li><div><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=19,label_exp=!master/440730//consoleText">AXIS_VARIABLE=19,label_exp=!master #440730</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-19-225] which is computer hudson.slaves.SlaveComputer@714fc773 and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129) [...]

2021-08-02 09:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/8609/">test-portal-acceptance-pullrequest(master)#8609</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8609/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550970996">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-08-02[00:28:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/1701/">publish-testray-report#1701</a><br/></div></div>

2021-08-02 09:50 UTC, weller0246 commented
ci:test:saml:nocompile

2021-08-02 09:51 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-08-02 09:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6265/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6265/jenkins-report.html">here</a>.</b></p>

2021-08-02 13:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 6 out of 9 jobs passed in 3 hours 16 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2168">Acceptance Upstream DXP (master) #2168</a></p><details><summary><strong>ci:test:saml - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6265/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/392483/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/390940/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/390935/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/392481/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/390934/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/390937/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/390936/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/390939/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6265/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/390940/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>6 Tests Passed.<br/>0 Tests Failed.</p></div><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/390940//consoleText">AXIS_VARIABLE=10,label_exp=!master #390940</a><pre><code>Build was aborted</code></pre></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/390940//consoleText">AXIS_VARIABLE=3,label_exp=!master #390940</a><pre><code>Build was aborted</code></pre></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/390940//consoleText">AXIS_VARIABLE=6,label_exp=!master #390940</a><pre><code>Build was aborted</code></pre></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/390940//consoleText">AXIS_VARIABLE=8,label_exp=!master #390940</a><pre><code>Build was aborted</code></pre></div></li><li>...</li></ol><strong>Click <a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/390940/testReport">here</a> for more failures.</strong></div></li><li><div><h5><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/392483/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>8 Tests Passed.<br/>9 Tests Failed.</p></div><ol><li><div><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=15,label_exp=!master/392483//consoleText">AXIS_VARIABLE=15,label_exp=!master #392483</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-19-83] which is computer hudson.slaves.SlaveComputer@7c933780 and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute Scripts' marked build as failure
Finished: FAILURE</code></pre></div></li><li><div><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=19,label_exp=!master/392483//consoleText">AXIS_VARIABLE=19,label_exp=!master #392483</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStep [...]

2021-08-02 13:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6265/">test-portal-acceptance-pullrequest(master)#6265</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6265/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551014655">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-08-02[02:53:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/1793/">publish-testray-report#1793</a><br/></div></div>

2021-08-02 13:34 UTC, weller0246 commented
ci:test:saml:nocompile

2021-08-02 13:34 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-08-02 13:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/39/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/39/jenkins-report.html">here</a>.</b></p>

2021-08-02 15:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 6 out of 9 jobs passed in 2 hours 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2168">Acceptance Upstream DXP (master) #2168</a></p><details><summary><strong>ci:test:saml - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/39/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15586/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25875/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25874/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/364303/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25872/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/745/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25873/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440045/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/39/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15586/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>9 Tests Passed.<br/>8 Tests Failed.</p></div><ol><li><div><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/15586//consoleText">AXIS_VARIABLE=1,label_exp=!master #15586</a><pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':runPoshi'.
     [exec] &gt; There were failing tests. See the report at: file:///opt/dev/projects/github/liferay-portal/portal-web/tests/index.html
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED in 14m 19s
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/portal-web/build/reports/profile/profile-2021-08-03-11-16-08.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] Result: 1
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-portal/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1_label_exp=!master/builds/15586
     [copy] Copying 3 files to /opt/dev/projects/github/liferay-portal/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1_label_exp=!master/builds/15586/screenshots
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1805498695.properties

clean-up-selenium-driver:
     [exec] chromedriver: no process found
     [exec] Result: 1
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1805498695.properties

print-elasticsearch-indices:
     [echo] Unable to print Elasticsearch indices at localhost:9201
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1805498695.properties

clean-up-logs:
 [parallel] 2021-08-03 18:30:51.837 INFO  [main][ThemeHotDeployListener:171] 1 theme for speedwell-theme was unregistered
 [parallel] 2021-08-03 18:30:52.405 INFO  [main][ThemeHotDeployListener:171] 1 theme for admin-theme was unregistered
 [parallel] 2021-08-03 18:30:53.327 INFO  [main][ThemeHotDeployListener:171] 1 theme for classic-theme was unregistered
 [parallel] 2021-08-03 18:30:53.724 INFO  [main][ThemeHotDeployListener:171] 1 theme for solution-theme was unregistered
 [parallel] 2021-08-03 18:30:53.827 INFO  [main][ThemeHotDeployListener:171] 1 theme for minium-theme was unregistered
 [parallel] 2021-08-03 18:31:13.387 INFO  [main][ThemeHotDeployListener:171] 1 theme for solution-theme was unregistered</code></pre></div></li><li><div><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/15586//consoleText">AXIS_VARIABLE=12,label_exp=!master #15586</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-16-116] which is computer hudson.slaves.SlaveComputer@303f99cc and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuil [...]

2021-08-02 15:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/39/">test-portal-acceptance-pullrequest(master)#39</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/39/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551040987">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-08-02[06:35:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/134/">publish-testray-report#134</a><br/></div></div>

2021-08-02 17:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4534/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-5-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4534/jenkins-report.html">here</a>.</b></p>

2021-08-02 17:26 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 0 out of 1 jobs passed in 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cb912889719a27e3dff73a0501155c0f36610f9">7cb912889719a27e3dff73a0501155c0f36610f9</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2168">Acceptance Upstream DXP (master) #2168</a></p><details><summary><strong>ci:test:saml - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4534/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-5-1.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4534/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4534/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>Build was aborted</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-08-02 17:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4534/">test-portal-acceptance-pullrequest(master)#4534</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-5-1.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4534/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551073863">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-08-02[10:06:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-5-1.liferay.com/job/publish-testray-report/2599/">publish-testray-report#2599</a><br/></div></div>

2021-08-03 07:49 UTC, weller0246 commented
ci:test:saml:nocompile

2021-08-03 07:49 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-08-03 08:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/333/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/333/jenkins-report.html">here</a>.</b></p>

2021-08-03 09:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 7 out of 9 jobs passed in 1 hour 32 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2172">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1287401_333</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d75a749f503bcaa193680fefda7da441807476a3">d75a749f503bcaa193680fefda7da441807476a3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/61815a0f9c81d83f62c4d570f193385bef737ef3">61815a0f9c81d83f62c4d570f193385bef737ef3</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2171">Acceptance Upstream DXP (master) #2171</a></p><details><summary><strong>ci:test:saml - 7 out of 9 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/333/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26031/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>7 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/746/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/748/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26030/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/744/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/747/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/745/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3463/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/333/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26031/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>47 Tests Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/26031//consoleText">AXIS_VARIABLE=5,label_exp=!master #26031</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/26031//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout_">LocalFile.SAML#AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/333/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/333/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/333/functional-tomcat90-mysql57-jdk8/0/5/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/26031//consoleText">AXIS_VARIABLE=6,label_exp=!master #26031</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/26031//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExistsAfterSPSessionTimeout_">LocalFile.SAML#AssertSSOSessionExistsAfterSPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/333/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/333/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/333/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/26031//consoleText">AXIS_VARIABLE=7,label_exp=!master #26031</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/26031//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExpiresAfterMaximumSessionAge_">LocalFile.SAML#AssertSSOSessionExpiresAfterMaximumSessionAge</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/333/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/333/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/333/functional-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-08-03 09:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/333/">test-portal-acceptance-pullrequest(master)#333</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/333/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551169697">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-08-03[00:49:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/979/">publish-testray-report#979</a><br/></div></div>

2021-08-03 09:33 UTC, weller0246 commented
@gaborlovasdotcom  @ferenconodiD  please review my code and tell me your opinion before forwarding

2021-08-03 14:22 UTC, gaborlovasdotcom requested changes
Please apply the changes in the comments.

2021-08-03 14:22 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
Please add property to limit your test case to use only a single tomcat instance via:
property app.server.bundles.size = "0";

2021-08-03 14:22 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +	@description = "This is a use case for LPS-88924 using virtual instance"
Please use the suffix format as it is in other test cases: " - Using virtual instances" Example in L#1897

2021-08-03 16:03 UTC, gaborlovasdotcom commented
@weller0246 Ticket ID is missing from the PR's name.

2021-08-03 17:37 UTC, gaborlovasdotcom approved these changes
LGTM!

2021-08-03 17:38 UTC, gaborlovasdotcom commented
ci:test:saml:nocompile

2021-08-03 17:39 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-08-03 18:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/77/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/77/jenkins-report.html">here</a>.</b></p>

2021-08-03 20:14 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 7 out of 9 jobs passed in 2 hours 35 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2172">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1267401_77</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d75a749f503bcaa193680fefda7da441807476a3">d75a749f503bcaa193680fefda7da441807476a3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/61815a0f9c81d83f62c4d570f193385bef737ef3">61815a0f9c81d83f62c4d570f193385bef737ef3</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2171">Acceptance Upstream DXP (master) #2171</a></p><details><summary><strong>ci:test:saml - 7 out of 9 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/77/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1018/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>7 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3631/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6849/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3632/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/887/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/888/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3630/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3633/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/77/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1018/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>47 Tests Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/1018//consoleText">AXIS_VARIABLE=5,label_exp=!master #1018</a><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/1018//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout_">LocalFile.SAML#AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-26/test-portal-acceptance-pullrequest(master)/77/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-26/test-portal-acceptance-pullrequest(master)/77/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-26/test-portal-acceptance-pullrequest(master)/77/functional-tomcat90-mysql57-jdk8/0/5/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/1018//consoleText">AXIS_VARIABLE=6,label_exp=!master #1018</a><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/1018//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExistsAfterSPSessionTimeout_">LocalFile.SAML#AssertSSOSessionExistsAfterSPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-26/test-portal-acceptance-pullrequest(master)/77/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-26/test-portal-acceptance-pullrequest(master)/77/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-26/test-portal-acceptance-pullrequest(master)/77/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/1018//consoleText">AXIS_VARIABLE=7,label_exp=!master #1018</a><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/1018//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExpiresAfterMaximumSessionAge_">LocalFile.SAML#AssertSSOSessionExpiresAfterMaximumSessionAge</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-26/test-portal-acceptance-pullrequest(master)/77/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-26/test-portal-acceptance-pullrequest(master)/77/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-26/test-portal-acceptance-pullrequest(master)/77/functional-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-08-03 20:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/77/">test-portal-acceptance-pullrequest(master)#77</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/77/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551259464">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-08-03[10:39:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/255/">publish-testray-report#255</a><br/></div></div>

2021-08-04 07:45 UTC, ferenconodiD approved these changes
LGTM!

2021-08-04 07:58 UTC, gaborlovasdotcom commented
ci:forward

2021-08-04 07:58 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-04 07:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/66/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-source-format/builds/66/jenkins-report.html">here</a>.</b></p>

2021-08-04 08:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d86484df4496658d12f06d7d889a2dc20be76d94">d86484df4496658d12f06d7d889a2dc20be76d94</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/weller0246/liferay-portal/tree/LPS-136416">LPS-136416</a><br/>Branch GIT ID: <a href="https://github.com/weller0246/liferay-portal/commit/cdccfd9915928c6945e56a9c5ab09520b2057ff2">cdccfd9915928c6945e56a9c5ab09520b2057ff2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/66/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/66/jenkins-report.html">here</a>.</h5></details></html>

2021-08-04 08:01 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-29.liferay.com/job/test-portal-source-format/66//consoleFull)

2021-08-04 08:01 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105091
[Console](https://test-1-29.liferay.com/job/test-portal-source-format/66//consoleFull)

2021-08-04 08:01 UTC, closed without merging

2021-08-04 08:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/66/">test-portal-source-format#66</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/66/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551358224">[master] ci:test:sf - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-08-04[00:58:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/255/">publish-testray-report#255</a><br/></div></div>

2021-08-04 08:02 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/105091

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/81//consoleFull)

2021-08-04 08:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/81/">test-portal-acceptance-pullrequest(master)#81</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/81/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/128">gaborlovasdotcom#128</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551358243">[master] ci:test:relevant - weller0246 &gt; gaborlovasdotcom - PR#128 - 2021-08-04[00:58:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/256/">publish-testray-report#256</a><br/></div></div>