LPS-133091 Adding new SAML test cases
gaborlovasdotcom/liferay-portal pull request #135
Opened 2021-08-05 08:56 UTC by ferenconodiD

[LPS-133091](https://issues.liferay.com/browse/LPS-133091)

2021-08-05 08:56 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-08-05 08:58 UTC, ferenconodiD commented
ci:test:sf

2021-08-05 08:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/98/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-source-format/builds/98/jenkins-report.html">here</a>.</b></p>

2021-08-05 09:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bdb4d1466b03471e889bb4d2a1f8357974b72e68">bdb4d1466b03471e889bb4d2a1f8357974b72e68</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ferenconodiD/liferay-portal/tree/master-lps-133091">master-lps-133091</a><br/>Branch GIT ID: <a href="https://github.com/ferenconodiD/liferay-portal/commit/2925f52ad5946f22e4bf55568664cedb6d7773ed">2925f52ad5946f22e4bf55568664cedb6d7773ed</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/98/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/98/jenkins-report.html">here</a>.</h5></details></html>

2021-08-05 09:04 UTC, ferenconodiD commented
ci:test:security:nocompile

2021-08-05 09:04 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-08-05 09:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/98/">test-portal-source-format#98</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/98/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551579955">[master] ci:test:sf - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-05[01:58:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/327/">publish-testray-report#327</a><br/></div></div>

2021-08-05 09:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3449/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3449/jenkins-report.html">here</a>.</b></p>

2021-08-05 10:17 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 0 out of 2 jobs passed in 1 hour 13 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2183">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1257401_3449</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bdb4d1466b03471e889bb4d2a1f8357974b72e68">bdb4d1466b03471e889bb4d2a1f8357974b72e68</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1a0623305850ea713750fa058658e074d5f0f1e4">1a0623305850ea713750fa058658e074d5f0f1e4</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2182">Acceptance Upstream DXP (master) #2182</a></p><details><summary><strong>ci:test:security - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3449/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26609/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3449/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26609/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>4 Tests Passed.<br/>4 Tests Failed.</p></div><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/26609//consoleText">AXIS_VARIABLE=0,label_exp=!master #26609</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/26609//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeEmailAddressUsedForUserMatching_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeEmailAddressUsedForUserMatching</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeEmailAddressUsedForUserMatching/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeEmailAddressUsedForUserMatching/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/26609//consoleText">AXIS_VARIABLE=1,label_exp=!master #26609</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/26609//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatching_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatching</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatching/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatching/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/26609//consoleText">AXIS_VARIABLE=2,label_exp=!master #26609</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/26609//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/26609//consoleText">AXIS_VARIABLE=3,label_exp=!master #26609</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/26609//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeUUIDUsedForUserMatching_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeUUIDUsedForUserMatching</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/3/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeUUIDUsedForUserMatching/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/3/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeUUIDUsedForUserMatching/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-25/test-portal-acceptance-pullrequest(master)/3449/functional-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol><strong>Click <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26609/testReport">here</a> for more failures.</strong></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-accep [...]

2021-08-05 10:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3449/">test-portal-acceptance-pullrequest(master)#3449</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3449/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551581784">[master] ci:test:security - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-05[02:04:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9724/">publish-testray-report#9724</a><br/></div></div>

2021-08-05 11:13 UTC, ferenconodiD commented
ci:sf:test

2021-08-05 11:16 UTC, ferenconodiD commented
ci:test:sf

2021-08-05 11:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/5953/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-portal-source-format/builds/5953/jenkins-report.html">here</a>.</b></p>

2021-08-05 11:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bdb4d1466b03471e889bb4d2a1f8357974b72e68">bdb4d1466b03471e889bb4d2a1f8357974b72e68</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ferenconodiD/liferay-portal/tree/master-lps-133091">master-lps-133091</a><br/>Branch GIT ID: <a href="https://github.com/ferenconodiD/liferay-portal/commit/424927f74563da5c77324b009726842af6433396">424927f74563da5c77324b009726842af6433396</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5953/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5953/jenkins-report.html">here</a>.</h5></details></html>

2021-08-05 11:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5953/">test-portal-source-format#5953</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5953/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551585572">[master] ci:test:sf - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-05[04:17:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/1733/">publish-testray-report#1733</a><br/></div></div>

2021-08-05 11:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4559/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-5-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4559/jenkins-report.html">here</a>.</b></p>

2021-08-05 13:45 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 0 out of 2 jobs passed in 1 hour 56 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2183">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:5017401_4559</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bdb4d1466b03471e889bb4d2a1f8357974b72e68">bdb4d1466b03471e889bb4d2a1f8357974b72e68</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1a0623305850ea713750fa058658e074d5f0f1e4">1a0623305850ea713750fa058658e074d5f0f1e4</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2182">Acceptance Upstream DXP (master) #2182</a></p><details><summary><strong>ci:test:security - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4559/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/33621/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-5-1.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4559/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/33621/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>4 Tests Passed.<br/>4 Tests Failed.</p></div><ol><li><div><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/33621//consoleText">AXIS_VARIABLE=0,label_exp=!master #33621</a><ol><li><div><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/33621//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeEmailAddressUsedForUserMatching_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeEmailAddressUsedForUserMatching</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeEmailAddressUsedForUserMatching/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeEmailAddressUsedForUserMatching/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/33621//consoleText">AXIS_VARIABLE=1,label_exp=!master #33621</a><ol><li><div><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/33621//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatching_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatching</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatching/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatching/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/33621//consoleText">AXIS_VARIABLE=2,label_exp=!master #33621</a><ol><li><div><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/33621//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/33621//consoleText">AXIS_VARIABLE=3,label_exp=!master #33621</a><ol><li><div><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/33621//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeUUIDUsedForUserMatching_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeUUIDUsedForUserMatching</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/3/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeUUIDUsedForUserMatching/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/3/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeUUIDUsedForUserMatching/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-5-1/test-portal-acceptance-pullrequest(master)/4559/functional-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol><strong>Click <a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/33621/testReport">here</a> for more failures.</strong></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master [...]

2021-08-05 13:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4559/">test-portal-acceptance-pullrequest(master)#4559</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-5-1.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4559/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551605292">[master] ci:test:security - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-05[04:49:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-5-1.liferay.com/job/publish-testray-report/2663/">publish-testray-report#2663</a><br/></div></div>

2021-08-06 09:58 UTC, ferenconodiD commented
ci:test:sf

2021-08-06 09:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/725/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-source-format/builds/725/jenkins-report.html">here</a>.</b></p>

2021-08-06 10:01 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/afdfbfad3b5db500d2bd327905f157177b718653">afdfbfad3b5db500d2bd327905f157177b718653</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ferenconodiD/liferay-portal/tree/master-lps-133091">master-lps-133091</a><br/>Branch GIT ID: <a href="https://github.com/ferenconodiD/liferay-portal/commit/3daa01ba5d0674fefb5b1f13f85d8044302a38cf">3daa01ba5d0674fefb5b1f13f85d8044302a38cf</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/725/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/725/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase expected:&lt;... days ago it worked
     [java] [
     [java] 		//AssertConsoleTextPresent(value1 = "Resolving user with user field expression: emailAddress");
     [java] 
     [java] 	\}
     [java] 
     [java] 	@description = "LPS-123218 TC-4: SP initiated login, using screenName for user matching - Using virtual instances"
     [java] 	@priority = "4"
     [java] 	test ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatching \{
     [java] 		property app.server.bundles.size = "0";
     [java] 		property portal.upstream = "feri";
     [java] 		property test.name.skip.portal.instance = "SAML#ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatching";
     [java] 
     [java] 		// For local testing
     [java] 
     [java] 		var identityProviderEntityId = "samlidp3";
     [java] 		var serviceProviderEntityId = "samlsp3";
     [java] 
     [java] 		SAML.enableSAMLDebugLogs();
     [java] 
     [java] 		// Add new virtual instance and setup SAML link between IdP and SP
     [java] 
     [java] 		SAML.addVirtualInstances(virtualHosts = "www.able.com");
     [java] 
     [java] 		SAML.setupIDP(
     [java] 			idpURL = "http://localhost:8080",
     [java] 			samlEntityID = "\$\{identityProviderEntityId\}",
     [java] 			userEmailAddress = "test@liferay.com");
     [java] 
     [java] 		SAML.setupSP(
     [java] 			encryptionCertificate = "true",
     [java] 			samlEntityID = "\$\{serviceProviderEntityId\}",
     [java] 			spURL = "http://www.able.com:8080",
     [java] 			userEmailAddress = "test@www.able.com");
     [java] 
     [java] 		SAML.addIDPConfigurationsToServiceProvider(
     [java] 			idpAttributeMapping = "screenName,UUID,emailAddress,firstName,lastName",
     [java] 			idpEntityID = "\$\{identityProviderEntityId\}",
     [java] 			idpKeepAliveURL = "http://localhost:8080/c/portal/saml/keep_alive",
     [java] 			idpURL = "http://localhost:8080",
     [java] 			nameIdentifierFormat = "Email Address",
     [java] 			spURL = "http://www.able.com:8080",
     [java] 			userEmailAddress = "test@www.able.com",
     [java] 			userMatchingAttributeIndex = "0",
     [java] 			userResolution = "attribute");
     [java] 
     [java] 		SAML.enableSPRoles(
     [java] 			samlEntityID = "\$\{serviceProviderEntityId\}",</code></pre></details></html>

2021-08-06 10:07 UTC, ferenconodiD commented
ci:test:sf

2021-08-06 10:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/104/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-source-format/builds/104/jenkins-report.html">here</a>.</b></p>

2021-08-06 10:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/afdfbfad3b5db500d2bd327905f157177b718653">afdfbfad3b5db500d2bd327905f157177b718653</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ferenconodiD/liferay-portal/tree/master-lps-133091">master-lps-133091</a><br/>Branch GIT ID: <a href="https://github.com/ferenconodiD/liferay-portal/commit/1309954f43d138ac0ef603884f7029e224eaf94f">1309954f43d138ac0ef603884f7029e224eaf94f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/104/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/104/jenkins-report.html">here</a>.</h5></details></html>

2021-08-06 10:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4563/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-5-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4563/jenkins-report.html">here</a>.</b></p>

2021-08-06 10:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 0 out of 1 jobs passed in 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/afdfbfad3b5db500d2bd327905f157177b718653">afdfbfad3b5db500d2bd327905f157177b718653</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39d9dc5f1957d6d8775c881b0170a78d918c043f">39d9dc5f1957d6d8775c881b0170a78d918c043f</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2187">Acceptance Upstream DXP (master) #2187</a></p><details><summary><strong>ci:test:security - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4563/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-5-1.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4563/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4563/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] * Where:
     [exec] Build file '/opt/dev/projects/github/liferay-portal/modules/profile-dxp.gradle' line: 48
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':checkoutDXPScript'.
     [exec] &gt; Process 'command 'git'' finished with non-zero exit value 128
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkoutDXPScript'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:208)
     [exec] 	at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:263)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
     [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter\$1.executeTask(EventFiringTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter\$1.call(EventFiringTaskExecuter.java:55)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter\$1.call(EventFiringTaskExecuter.java:52)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor\$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-08-06 10:41 UTC, gaborlovasdotcom commented
ci:test:security:nocompile

2021-08-06 10:41 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-08-06 10:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/115/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/115/jenkins-report.html">here</a>.</b></p>

2021-08-06 11:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/4563/">test-portal-acceptance-pullrequest(master)#4563</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-5-1.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4563/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551812837">[master] ci:test:security - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-06[03:09:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-5-1.liferay.com/job/publish-testray-report/2682/">publish-testray-report#2682</a><br/></div></div>

2021-08-06 13:15 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 0 out of 2 jobs passed in 2 hours 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/afdfbfad3b5db500d2bd327905f157177b718653">afdfbfad3b5db500d2bd327905f157177b718653</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/afdfbfad3b5db500d2bd327905f157177b718653">afdfbfad3b5db500d2bd327905f157177b718653</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2188">Acceptance Upstream DXP (master) #2188</a></p><details><summary><strong>ci:test:security - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/115/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/492/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/115/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/492/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>3 Tests Passed.<br/>0 Tests Failed.</p></div><ol><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/492//consoleText">AXIS_VARIABLE=3,label_exp=!master #492</a><pre><code>Build was aborted</code></pre></div></li><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/492//consoleText">AXIS_VARIABLE=2,label_exp=!master #492</a><ol><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/492//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/115/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/115/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-30/test-portal-acceptance-pullrequest(master)/115/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-08-06 14:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/104/">test-portal-source-format#104</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/104/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551829363">[master] ci:test:sf - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-06[03:07:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/310/">publish-testray-report#310</a><br/></div></div>

2021-08-06 15:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/725/">test-portal-source-format#725</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/725/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551831976">[master] ci:test:sf - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-06[02:58:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/1589/">publish-testray-report#1589</a><br/></div></div>

2021-08-09 14:34 UTC, ferenconodiD commented
ci:test:sf

2021-08-09 14:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/44/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com//userContent/jobs/test-portal-source-format/builds/44/jenkins-report.html">here</a>.</b></p>

2021-08-09 14:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7dc0791fd9952d8cd0fe3649dae88a9e166c7975">7dc0791fd9952d8cd0fe3649dae88a9e166c7975</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ferenconodiD/liferay-portal/tree/master-lps-133091">master-lps-133091</a><br/>Branch GIT ID: <a href="https://github.com/ferenconodiD/liferay-portal/commit/50001824813650439251042c4c5a1be9d23ab3be">50001824813650439251042c4c5a1be9d23ab3be</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/44/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/44/jenkins-report.html">here</a>.</h5></details></html>

2021-08-09 14:37 UTC, ferenconodiD commented
ci:test:security:nocompile

2021-08-09 14:37 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-08-09 14:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/437/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/437/jenkins-report.html">here</a>.</b></p>

2021-08-09 15:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 0 out of 2 jobs passed in 1 hour 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8d17d473200786491e38ac7f6758b303db2c28f6">8d17d473200786491e38ac7f6758b303db2c28f6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8d17d473200786491e38ac7f6758b303db2c28f6">8d17d473200786491e38ac7f6758b303db2c28f6</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2196">Acceptance Upstream DXP (master) #2196</a></p><details><summary><strong>ci:test:security - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/437/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/879/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/437/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/879/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>11 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/879//consoleText">AXIS_VARIABLE=3,label_exp=!master #879</a><ol><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/879//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/437/functional-tomcat90-mysql57-jdk8/0/3/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/437/functional-tomcat90-mysql57-jdk8/0/3/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/437/functional-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-08-09 16:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/44/">test-portal-source-format#44</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/44/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552216139">[master] ci:test:sf - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-09[07:34:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/119/">publish-testray-report#119</a><br/></div></div>

2021-08-11 07:43 UTC, ferenconodiD commented
ci:test:sf

2021-08-11 07:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3261/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/3261/jenkins-report.html">here</a>.</b></p>

2021-08-11 07:55 UTC, ferenconodiD commented
ci:test:security:nocompile

2021-08-11 07:55 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-08-11 07:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3261/">test-portal-source-format#3261</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3261/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552606421">[master] ci:test:sf - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-11[00:44:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9888/">publish-testray-report#9888</a><br/></div></div>

2021-08-11 07:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/485/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/485/jenkins-report.html">here</a>.</b></p>

2021-08-11 10:03 UTC, gaborlovasdotcom requested changes
Review done, see my notes on the code.

2021-08-11 10:03 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +		var serviceProviderEntityId = "samlsp";
Nice! 👍

2021-08-11 10:19 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 0 out of 2 jobs passed in 2 hours 23 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2206">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1287401_485</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3757f7605fc5cbd8d6f8125454a32f0aeee5d61a">3757f7605fc5cbd8d6f8125454a32f0aeee5d61a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dedd00197744b6f5a805793b296d9c8da5c105e0">dedd00197744b6f5a805793b296d9c8da5c105e0</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2204">Acceptance Upstream DXP (master) #2204</a></p><details><summary><strong>ci:test:security - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/485/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2683/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/485/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2683/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>3 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=4,label_exp=!master/2683//consoleText">AXIS_VARIABLE=4,label_exp=!master #2683</a><pre><code>Build was aborted</code></pre></div></li><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/2683//consoleText">AXIS_VARIABLE=2,label_exp=!master #2683</a><pre><code>[beanshell] Remote execution starting with 1 threads.
[beanshell] Executing commands: ssh -o NumberOfPasswordPrompts=0 test-1-29 'mkdir -p "/mnt/mfs-hdd1-10.0.10/jenkins/testray-results/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/485/functional-tomcat90-mysql57-jdk8/0/2"'
[beanshell] Average thread duration: 222ms
[beanshell] Busy slaves:0
[beanshell] Finished slaves:1
[beanshell] Target slaves:1
[beanshell] Total duration: 223
[beanshell] Remote execution completed in 224ms.
[beanshell] Executing commands: rsync -aqz --chmod=go=rx "/opt/dev/projects/github/liferay-jenkins-ee/testray/logs"/* "test-1-29::testray-results/production/logs/"
[beanshell] Uploaded https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest%28master%29/485/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz
[stopwatch] [run.current.job: 25.917 sec]
[beanshell] Created cache file in /tmp/jenkins-cached-files/731284198.txt

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:13483: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-portal-acceptance-batch.xml:180: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:9849: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:10187: Sourced file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : Typed variable declaration : Method Invocation GitWorkingDirectoryFactory.newGitWorkingDirectory : at Line: 80 : in file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : GitWorkingDirectoryFactory .newGitWorkingDirectory ( project .getProperty ( "branch.name" ) , project .getProperty ( "dir" ) , project .getProperty ( "repository" ) ) 

Called from method: getGitWorkingDirectory : at Line: 83 : in file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : getGitWorkingDirectory ( ) 
Target exception: java.lang.RuntimeException: Unable to get list of Git remotes
fatal: not a git repository (or any parent up to mount point /opt/dev/projects)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).</code></pre></div></li><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/2683//consoleText">AXIS_VARIABLE=3,label_exp=!master #2683</a><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/2683//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/3/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/3/LocalFile.SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-08-11 10:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/485/">test-portal-acceptance-pullrequest(master)#485</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/485/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552619928">[master] ci:test:security - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-11[00:56:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/1364/">publish-testray-report#1364</a><br/></div></div>

2021-08-12 14:09 UTC, ferenconodiD commented
ci:test:sf

2021-08-12 14:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/108/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com//userContent/jobs/test-portal-source-format/builds/108/jenkins-report.html">here</a>.</b></p>

2021-08-12 14:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/85886f2cb10251d59a08d69d48bd523b835e2fcb">85886f2cb10251d59a08d69d48bd523b835e2fcb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ferenconodiD/liferay-portal/tree/master-lps-133091">master-lps-133091</a><br/>Branch GIT ID: <a href="https://github.com/ferenconodiD/liferay-portal/commit/5b0ad2bb3c946c20b6a6877bdeb1f001ce7f97cc">5b0ad2bb3c946c20b6a6877bdeb1f001ce7f97cc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/108/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/108/jenkins-report.html">here</a>.</h5></details></html>

2021-08-12 14:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/108/">test-portal-source-format#108</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/108/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552882195">[master] ci:test:sf - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-12[07:09:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/321/">publish-testray-report#321</a><br/></div></div>

2021-08-12 16:28 UTC, weller0246 requested changes

2021-08-12 16:28 UTC, weller0246 commented on portal-web/test/functional/com/liferay/portalweb/macros/SAML.macro
> +		// Add new test user
I think this comment is not necessary as the description says the same sentence

2021-08-12 16:28 UTC, weller0246 commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +		// For local testing
Is this comment necessary in the repository?

2021-08-13 08:09 UTC, ferenconodiD commented
ci:test:sf

2021-08-13 08:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/226/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-source-format/builds/226/jenkins-report.html">here</a>.</b></p>

2021-08-13 08:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/93d9ee301f312b83377ba09028fd52311dc9d385">93d9ee301f312b83377ba09028fd52311dc9d385</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ferenconodiD/liferay-portal/tree/master-lps-133091">master-lps-133091</a><br/>Branch GIT ID: <a href="https://github.com/ferenconodiD/liferay-portal/commit/3aee58da03420878969ebda8798fd1744023c279">3aee58da03420878969ebda8798fd1744023c279</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/226/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/226/jenkins-report.html">here</a>.</h5></details></html>

2021-08-13 08:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/226/">test-portal-source-format#226</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/226/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1553139361">[master] ci:test:sf - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-13[01:10:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/696/">publish-testray-report#696</a><br/></div></div>

2021-08-13 08:17 UTC, weller0246 approved these changes

2021-08-13 10:03 UTC, gaborlovasdotcom approved these changes
LGTM!

2021-08-13 10:04 UTC, gaborlovasdotcom commented
ci:test:saml:nocompile

2021-08-13 10:04 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-08-13 10:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/818/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/818/jenkins-report.html">here</a>.</b></p>

2021-08-13 11:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 6 out of 9 jobs passed in 1 hour 16 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2213">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1027401_818</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/93d9ee301f312b83377ba09028fd52311dc9d385">93d9ee301f312b83377ba09028fd52311dc9d385</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5fbca7f37fa32d3d174de5ae82121eb531d9795e">5fbca7f37fa32d3d174de5ae82121eb531d9795e</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2212">Acceptance Upstream DXP (master) #2212</a></p><details><summary><strong>ci:test:saml - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/818/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1730/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3289/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3288/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1729/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3287/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1833/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1832/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/478593/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/818/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1730/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>47 Tests Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/1730//consoleText">AXIS_VARIABLE=6,label_exp=!master #1730</a><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/1730//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout_">LocalFile.SAML#AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.SAML_AssertSSOIdleSessionTakesPrecedenceOverIdPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/1730//consoleText">AXIS_VARIABLE=7,label_exp=!master #1730</a><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/1730//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExistsAfterSPSessionTimeout_">LocalFile.SAML#AssertSSOSessionExistsAfterSPSessionTimeout</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/7/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/1730//consoleText">AXIS_VARIABLE=8,label_exp=!master #1730</a><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/1730//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExpiresAfterMaximumSessionAge_">LocalFile.SAML#AssertSSOSessionExpiresAfterMaximumSessionAge</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/8/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/8/LocalFile.SAML_AssertSSOSessionExpiresAfterMaximumSessionAge/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/null/null/null/null/functional-tomcat90-mysql57-jdk8/0/8/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3289/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>39 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/3289//consoleText">AXIS_VARIABLE=7,label_exp=!master #3289</a><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=7,label_exp=!master/3289//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForUserMatchingMultipleIdP_">LocalFile.SAML#ViewSPInitiatedSSOWithSAMLAttributeScreenNameUsedForU [...]

2021-08-13 11:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/818/">test-portal-acceptance-pullrequest(master)#818</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/818/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1553150075">[master] ci:test:saml - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-13[03:11:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/1712/">publish-testray-report#1712</a><br/></div></div>

2021-08-13 12:16 UTC, gaborlovasdotcom commented
ci:forward

2021-08-13 12:16 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-13 12:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/124/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com//userContent/jobs/test-portal-source-format/builds/124/jenkins-report.html">here</a>.</b></p>

2021-08-13 12:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e13b6a462a1461a097b848bd1eef9790a838c831">e13b6a462a1461a097b848bd1eef9790a838c831</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ferenconodiD/liferay-portal/tree/master-lps-133091">master-lps-133091</a><br/>Branch GIT ID: <a href="https://github.com/ferenconodiD/liferay-portal/commit/7af3cf6a3f6218ed7b90b12015341bcb50df6caa">7af3cf6a3f6218ed7b90b12015341bcb50df6caa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/124/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/124/jenkins-report.html">here</a>.</h5></details></html>

2021-08-13 12:19 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-31.liferay.com/job/test-portal-source-format/124//consoleFull)

2021-08-13 12:19 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105540
[Console](https://test-1-31.liferay.com/job/test-portal-source-format/124//consoleFull)

2021-08-13 12:19 UTC, closed without merging

2021-08-13 12:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/132/">test-portal-acceptance-pullrequest(master)#132</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/132/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1553154848">[master] ci:test:relevant - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-13[05:16:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/357/">publish-testray-report#357</a><br/></div></div>

2021-08-13 12:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/124/">test-portal-source-format#124</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/124/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/135">gaborlovasdotcom#135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1553154857">[master] ci:test:sf - ferenconodiD &gt; gaborlovasdotcom - PR#135 - 2021-08-13[05:16:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/358/">publish-testray-report#358</a><br/></div></div>