LPS-139114 Adding SAML - OAuth2 tests additional steps to remove from quarantine #153
gaborlovasdotcom/liferay-portal pull request #155
Opened 2021-09-16 09:30 UTC by weller0246

https://issues.liferay.com/browse/LPS-139114

2021-09-16 09:30 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-09-16 09:30 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-09-16 09:30 UTC, weller0246 commented
ci:test:security:nocompile

2021-09-16 09:30 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-09-16 09:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/322/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/322/jenkins-report.html">here</a>.</b></p>

2021-09-16 09:52 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 0 out of 2 jobs passed in 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1ff16e8938589891df0d6e796214f74446abfb">2e1ff16e8938589891df0d6e796214f74446abfb</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1ff16e8938589891df0d6e796214f74446abfb">2e1ff16e8938589891df0d6e796214f74446abfb</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2322">Acceptance Upstream DXP (master) #2322</a></p><details><summary><strong>ci:test:security - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/322/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4299/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/322/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4299/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/4299//consoleText">AXIS_VARIABLE=0 #4299</a><pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':writePoshiProperties'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED in 59s
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/portal-web/build/reports/profile/profile-2021-09-16-02-50-27.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] Result: 1
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:4948: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1736: Task [run-batch-test] failed after [1] attempts; giving up.
     [echo] Error messages:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1784: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12625: Warning: Could not find file /opt/dev/projects/github/liferay-portal/portal-web/test.generated.properties to copy.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1784: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12625: Warning: Could not find file /opt/dev/projects/github/liferay-portal/portal-web/test.generated.properties to copy.

record-testray-logs:
[beanshell] Created cache file in /tmp/jenkins-cached-files/1774942552.txt
[beanshell] Executing commands: time rsync -Iqs --timeout=1200 test-1-25-2:/tmp/dist/test-1-28/test-portal-acceptance-pullrequest\(master\)/322/dist/build-database.json /tmp/jenkins/test-1-26/test-portal-acceptance-pullrequest-batch\(master\)/0/4299/build-database.json
[beanshell] Unable to delete because file does not exist /opt/dev/projects/github/liferay-jenkins-ee/testray/logs
[beanshell] Created cache file in /tmp/jenkins-cached-files/1774942552.txt</code></pre></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/4299//consoleText">AXIS_VARIABLE=1 #4299</a><pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':writePoshiProperties'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED in 20s
     [exec] Result: 1
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:4948: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1736: Task [run-batch-test] failed after [1] attempts; giving up.
     [echo] Error messages:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1784: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12625: Warning: Could not find file /opt/dev/projects/github/liferay-portal/portal-web/test.generated.properties to copy.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1784: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12625: Warning: Could not find file /opt/dev/projects/github/liferay-portal/portal-web/test.generated.properties to copy.

record-testray-logs:
[beanshell] Created cache file in /tmp/jenkins-cached-files/-2008196251.txt
[beanshell] Executing commands: time rsync -Iqs --timeout=1200 test-1-25-2:/tmp/dist/test-1-28/test-portal-acceptance-pullrequest\(master\)/322/dist/build-database.json /tmp/jenkins/test-1-26/test-portal-acceptance-pullrequest-batch\(master\)/1/4299/build-database.json
[beanshell] Unable to delete because file does not exist /opt/dev/projects/github/liferay-jenkins-ee/testray/logs
[beanshell] Created cache file in /tmp/jenkins-cached-files/-2008196251.txt
[beanshell] Executing commands: git remote -v
[beanshell] Found Git remotes: origin, upstream
[beanshell] Remote execution starting with 1 threads.</code></pre></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-09-16 09:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/322/">test-portal-acceptance-pullrequest(master)#322</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/322/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/155">gaborlovasdotcom#155</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1561754495">[master] ci:test:security - weller0246 &gt; gaborlovasdotcom - PR#155 - 2021-09-16[02:30:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/846/">publish-testray-report#846</a><br/></div></div>

2021-09-16 10:51 UTC, weller0246 commented
ci:test:security:nocompile

2021-09-16 10:51 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-09-16 10:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/323/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/323/jenkins-report.html">here</a>.</b></p>

2021-09-16 11:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 0 out of 2 jobs passed in 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1ff16e8938589891df0d6e796214f74446abfb">2e1ff16e8938589891df0d6e796214f74446abfb</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1ff16e8938589891df0d6e796214f74446abfb">2e1ff16e8938589891df0d6e796214f74446abfb</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2322">Acceptance Upstream DXP (master) #2322</a></p><details><summary><strong>ci:test:security - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/323/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6060/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/323/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6060/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/6060//consoleText">AXIS_VARIABLE=0 #6060</a><pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':writePoshiProperties'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED in 19s
     [exec] Result: 1
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:4948: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1736: Task [run-batch-test] failed after [1] attempts; giving up.
     [echo] Error messages:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1784: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12625: Warning: Could not find file /opt/dev/projects/github/liferay-portal/portal-web/test.generated.properties to copy.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1784: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12625: Warning: Could not find file /opt/dev/projects/github/liferay-portal/portal-web/test.generated.properties to copy.

record-testray-logs:
[beanshell] Created cache file in /tmp/jenkins-cached-files/1283592539.txt
[beanshell] Executing commands: time rsync -Iqs --timeout=1200 test-1-26-51:/tmp/dist/test-1-28/test-portal-acceptance-pullrequest\(master\)/323/dist/build-database.json /tmp/jenkins/test-1-32/test-portal-acceptance-pullrequest-batch\(master\)/0/6060/build-database.json
[beanshell] Unable to delete because file does not exist /opt/dev/projects/github/liferay-jenkins-ee/testray/logs
[beanshell] Created cache file in /tmp/jenkins-cached-files/1283592539.txt
[beanshell] Executing commands: git remote -v
[beanshell] Found Git remotes: origin, upstream
[beanshell] Remote execution starting with 1 threads.</code></pre></div></li><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/6060//consoleText">AXIS_VARIABLE=1 #6060</a><pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':writePoshiProperties'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED in 19s
     [exec] 
     [exec] &gt; Task :writePoshiProperties FAILED
     [exec] Gradle build finished at 2021-09-16 11:03:52.096.
     [exec] 
     [exec] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
     [exec] Use '--warning-mode all' to show the individual deprecation warnings.
     [exec] See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
     [exec] 1 actionable task: 1 executed
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/portal-web/build/reports/profile/profile-2021-09-16-04-03-33.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] Result: 1
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:4948: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1736: Task [run-batch-test] failed after [1] attempts; giving up.
     [echo] Error messages:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1784: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12625: Warning: Could not find file /opt/dev/projects/github/liferay-portal/portal-web/test.generated.properties to copy.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1784: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12625: Warning: Could not find file /opt/dev/projects/github/liferay-portal/portal-web/test.generated.properties to copy.

record-testray-logs:</code></pre></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-09-16 11:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/323/">test-portal-acceptance-pullrequest(master)#323</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/323/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/155">gaborlovasdotcom#155</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1561807253">[master] ci:test:security - weller0246 &gt; gaborlovasdotcom - PR#155 - 2021-09-16[03:51:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/849/">publish-testray-report#849</a><br/></div></div>

2021-09-16 13:24 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/oauth2/OAuth2.path
> +	<td>//input[contains(@id,'url')]</td>
Please add a third <td> section here as seen for other  XPaths

2021-09-16 14:40 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-09-16 14:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/498/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/498/jenkins-report.html">here</a>.</b></p>

2021-09-16 15:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:security - 2 out of 2 jobs passed in 30 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1ff16e8938589891df0d6e796214f74446abfb">2e1ff16e8938589891df0d6e796214f74446abfb</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1ff16e8938589891df0d6e796214f74446abfb">2e1ff16e8938589891df0d6e796214f74446abfb</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2322">Acceptance Upstream DXP (master) #2322</a></p><details><summary><strong>ci:test:security - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/498/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5783/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/498/jenkins-report.html">here</a>.</h5></details></html>

2021-09-16 15:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/498/">test-portal-acceptance-pullrequest(master)#498</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/498/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/155">gaborlovasdotcom#155</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1561853660">[master] ci:test:security - weller0246 &gt; gaborlovasdotcom - PR#155 - 2021-09-16[07:41:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/1493/">publish-testray-report#1493</a><br/></div></div>

2021-09-16 15:51 UTC, gaborlovasdotcom requested changes
Looks good, there's one change request in macro what we should do.

2021-09-16 15:51 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +	@description = "This is a use case for LRQA-57574 TC-1: Combines SAML.CreateAndSyncUserAfterSAMLSetupWithMatchingScreenNameAttribute and Oauth2.AuthorizeExternalApplication to verify that the portal
Please use OAuth2 instead of Oauth2.

2021-09-16 15:51 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +			customPortalURL = "true");
Could you please refactor the test case / macro, to eliminate this new custom property?

2021-09-16 15:51 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +			customPortalURL = "true");
We could trick baseURL-»portalURL and refactor the OAuth2.addAndEditExternalApplication macro, to use portal.url only, when we don't define any value at test case level.

2021-09-16 15:51 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +	@description = "This is a use case for LRQA-57574 TC-2: Combines SAML.CreateAndSyncUserAfterSAMLSetupWithMatchingScreenNameAttribute and Oauth2.AuthorizeExternalApplication to verify that the portal
Please use OAuth2 instead of Oauth2 in similar texts.

2021-09-16 15:51 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +			customPortalURL = "true");
Same as above, we should try to avoid introducing new booleans into our tests.

2021-09-17 08:43 UTC, ferenconodiD commented
ci:test:sf

2021-09-17 08:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/349/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-source-format/builds/349/jenkins-report.html">here</a>.</b></p>

2021-09-17 08:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1fc6cd2ef5a22f8b59cfd402e4c32c5abd55d886">1fc6cd2ef5a22f8b59cfd402e4c32c5abd55d886</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/weller0246/liferay-portal/tree/LPS-139114">LPS-139114</a><br/>Branch GIT ID: <a href="https://github.com/weller0246/liferay-portal/commit/ea56d2b8bf4334f82e8a70c8868b068734cf20aa">ea56d2b8bf4334f82e8a70c8868b068734cf20aa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/349/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/349/jenkins-report.html">here</a>.</h5></details></html>

2021-09-17 08:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/349/">test-portal-source-format#349</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/349/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/155">gaborlovasdotcom#155</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1562041426">[master] ci:test:sf - weller0246 &gt; gaborlovasdotcom - PR#155 - 2021-09-17[01:44:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/1160/">publish-testray-report#1160</a><br/></div></div>

2021-09-17 08:55 UTC, ferenconodiD approved these changes
LGTM!

2021-09-17 13:21 UTC, gaborlovasdotcom approved these changes
LGTM!

2021-09-17 13:22 UTC, gaborlovasdotcom commented
ci:test:sf

2021-09-17 13:22 UTC, gaborlovasdotcom commented
ci:test:saml:nocompile

2021-09-17 13:22 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-09-17 13:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/264/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-source-format/builds/264/jenkins-report.html">here</a>.</b></p>

2021-09-17 13:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/350/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/350/jenkins-report.html">here</a>.</b></p>

2021-09-17 13:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/81cb74c61e87ef8b67eef23db95105fde6db4665">81cb74c61e87ef8b67eef23db95105fde6db4665</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/weller0246/liferay-portal/tree/LPS-139114">LPS-139114</a><br/>Branch GIT ID: <a href="https://github.com/weller0246/liferay-portal/commit/ea56d2b8bf4334f82e8a70c8868b068734cf20aa">ea56d2b8bf4334f82e8a70c8868b068734cf20aa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/264/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/264/jenkins-report.html">here</a>.</h5></details></html>

2021-09-17 13:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/264/">test-portal-source-format#264</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/264/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/155">gaborlovasdotcom#155</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1562140895">[master] ci:test:sf - weller0246 &gt; gaborlovasdotcom - PR#155 - 2021-09-17[06:22:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/901/">publish-testray-report#901</a><br/></div></div>

2021-09-17 14:25 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 6 out of 10 jobs passed in 1 hour 3 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2326">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1287401_350</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/779dea9f73ab9d49a67f92f2bcc3752e31eeb5f1">779dea9f73ab9d49a67f92f2bcc3752e31eeb5f1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1fc6cd2ef5a22f8b59cfd402e4c32c5abd55d886">1fc6cd2ef5a22f8b59cfd402e4c32c5abd55d886</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2325">Acceptance Upstream DXP (master) #2325</a></p><details><summary><strong>ci:test:saml - 6 out of 10 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/350/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4937/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4795/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6879/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4794/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6387/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6386/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6877/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6878/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4579/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/350/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4795/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></h5><div><h6>Job Results:</h6><p>16 Tests Passed.<br/>5 Tests Failed.</p></div><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=16/4795//consoleText">AXIS_VARIABLE=16 #4795</a><pre><code>print-jstack-logs:
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/jps_output
[stopwatch] [run.batch.test.action: 16:03.966 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1741: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1745: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13184: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:14060: Timeout: killed the sub-process
      [get] Getting: http://test-1-27/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=16/4795//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210917065923499.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210917065923499.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1234546755.properties</code></pre></div></li><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=17/4795//consoleText">AXIS_VARIABLE=17 #4795</a><pre><code>print-jstack-logs:
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/jps_output
[stopwatch] [run.batch.test.action: 15:59.593 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1741: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1745: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13184: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:14060: Timeout: killed the sub-process
      [get] Getting: http://test-1-27/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=17/4795//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210917070225187.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210917070225187.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null827437879.properties</code></pre></div></li><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=18/4795//consoleText">AXIS_VARIABLE=18 #4795</a><pre><code>print-jstack-logs:
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/jps_output
[stopwatch] [run.batch.test.action: 15:57.820 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1741: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1745: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while ex [...]

2021-09-17 14:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/350/">test-portal-acceptance-pullrequest(master)#350</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/350/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/155">gaborlovasdotcom#155</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1562152356">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#155 - 2021-09-17[06:22:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/902/">publish-testray-report#902</a><br/></div></div>

2021-09-17 15:06 UTC, gaborlovasdotcom commented
ci:forward

2021-09-17 15:06 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-09-17 15:06 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-09-17 15:07 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/forward-pullrequest/49//consoleFull)

2021-09-17 15:08 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/107417
[Console](https://test-1-28.liferay.com/job/forward-pullrequest/49//consoleFull)

2021-09-17 15:08 UTC, closed without merging