LRQA-70350 | master
gaborlovasdotcom/liferay-portal pull request #196
Opened 2021-11-03 20:09 UTC by Kvale1733

https://issues.liferay.com/browse/LRQA-70350

2021-11-03 20:09 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-11-03 20:09 UTC, Kvale1733 commented
ci:test:sf

2021-11-03 20:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/3981/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-portal-source-format/builds/3981/jenkins-report.html">here</a>.</b></p>

2021-11-03 20:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ba24d12465d9ea0c15cea177517f06d38f15f975">ba24d12465d9ea0c15cea177517f06d38f15f975</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Kvale1733/liferay-portal/tree/LRQA-70350">LRQA-70350</a><br/>Branch GIT ID: <a href="https://github.com/Kvale1733/liferay-portal/commit/b8fb9417ac550872691f21b99b70a4f27f958154">b8fb9417ac550872691f21b99b70a4f27f958154</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3981/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3981/jenkins-report.html">here</a>.</h5></details></html>

2021-11-03 20:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3981/">test-portal-source-format#3981</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3981/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/196">gaborlovasdotcom#196</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1575636117">[master] ci:test:sf - Kvale1733 &gt; gaborlovasdotcom - PR#196 - 2021-11-03[13:16:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/1758/">publish-testray-report#1758</a><br/></div></div>

2021-11-04 11:05 UTC, gaborlovasdotcom requested changes
Hi @Kvale1733 , I reviewed the namings, and they look good, but some of them are still too technical.
In these functional tests, we would like to express the goal of each test case from the business side, rather than the technical side.
I shared a few examples that I'm thinking about, feel free to modify or apply them.
I'm also waiting for @weller0246 and @ferenconodiD to review the possible test descriptions.

2021-11-04 11:05 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/security/login/Login.testcase
> +	@description = "This is a use case for LRQA-40911. Add SSO openId connect provider and assert user can logout and login with openID connect."
"Users could login and logout using OpenID Connect provider"

2021-11-04 11:05 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/security/login/Login.testcase
> +	@description = "This is a use case for LRQA-27622. Assert token based SSO can be enabled."
"Users could login using Token Based SSO"

2021-11-04 11:05 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/security/login/Login.testcase
> +	@description = "This is a use case for LRQA-27619. View authentication instance settings."
"Verify that LDAP and OpenSSO portlets are present at Instance Settings"

2021-11-04 15:58 UTC, weller0246 requested changes
Fixing the review comments from @gaborlovasdotcom side will cover everything from my side, keep up the good job! :)

2021-11-04 20:01 UTC, Kvale1733 commented
ci:test:sf

2021-11-04 20:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/3061/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-portal-source-format/builds/3061/jenkins-report.html">here</a>.</b></p>

2021-11-04 20:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 10 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/628dd273eb93deb7a3e8dd0625075012033fca73">628dd273eb93deb7a3e8dd0625075012033fca73</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Kvale1733/liferay-portal/tree/LRQA-70350">LRQA-70350</a><br/>Branch GIT ID: <a href="https://github.com/Kvale1733/liferay-portal/commit/e705c5afbd918f01b1b522a2e4c6c80f716f79ea">e705c5afbd918f01b1b522a2e4c6c80f716f79ea</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3061/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3061/jenkins-report.html">here</a>.</h5></details></html>

2021-11-04 20:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3061/">test-portal-source-format#3061</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3061/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/196">gaborlovasdotcom#196</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1576159254">[master] ci:test:sf - Kvale1733 &gt; gaborlovasdotcom - PR#196 - 2021-11-04[13:02:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/6955/">publish-testray-report#6955</a><br/></div></div>

2021-11-05 16:27 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/security/login/Login.testcase
> +	@description = "This is a use case for LRQA-48218. User should be redrected to the changed landing page upon login."
typo in redirected

2021-11-05 17:53 UTC, Kvale1733 commented
Typo has been fixed

2021-11-08 13:06 UTC, gaborlovasdotcom approved these changes
LGTM!

2021-11-08 13:47 UTC, weller0246 approved these changes

2021-11-09 11:58 UTC, ferenconodiD approved these changes
LGTM!

2021-11-09 11:59 UTC, ferenconodiD commented
ci:forward

2021-11-09 11:59 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-11-09 12:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/734/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-source-format/builds/734/jenkins-report.html">here</a>.</b></p>

2021-11-09 12:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2bb0e3cbdab90dacbfaa718f2d2bd2d10e54b850">2bb0e3cbdab90dacbfaa718f2d2bd2d10e54b850</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Kvale1733/liferay-portal/tree/LRQA-70350">LRQA-70350</a><br/>Branch GIT ID: <a href="https://github.com/Kvale1733/liferay-portal/commit/b376e892207afc4d5be08f45c4ec317ce716ced4">b376e892207afc4d5be08f45c4ec317ce716ced4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/734/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/734/jenkins-report.html">here</a>.</h5></details></html>

2021-11-09 12:02 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/734//consoleFull)

2021-11-09 12:02 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/109631
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/734//consoleFull)

2021-11-09 12:02 UTC, closed without merging

2021-11-09 12:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/826/">test-portal-acceptance-pullrequest(master)#826</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/826/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/196">gaborlovasdotcom#196</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1577716664">[master] ci:test:relevant - Kvale1733 &gt; gaborlovasdotcom - PR#196 - 2021-11-09[03:59:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/2513/">publish-testray-report#2513</a><br/></div></div>

2021-11-09 12:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/734/">test-portal-source-format#734</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/734/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/196">gaborlovasdotcom#196</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1577716673">[master] ci:test:sf - Kvale1733 &gt; gaborlovasdotcom - PR#196 - 2021-11-09[03:59:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/2514/">publish-testray-report#2514</a><br/></div></div>