LRQA-73647
gaborlovasdotcom/liferay-portal pull request #337
Opened 2022-03-07 14:43 UTC by weller0246

[LRQA-73647](https://issues.liferay.com/browse/LRQA-73647)

2022-03-07 14:43 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-07 14:47 UTC, weller0246 commented
ci:test:sf

2022-03-07 14:47 UTC, weller0246 commented
ci:test:staging:nocompile

2022-03-07 14:47 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-03-07 14:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/2022/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2022/jenkins-report.html">here</a>.</b></p>

2022-03-07 14:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0de64eb6649bc87190fe93e0ea01d194e31e065e">0de64eb6649bc87190fe93e0ea01d194e31e065e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/weller0246/liferay-portal/tree/LRQA-73647">LRQA-73647</a><br/>Branch GIT ID: <a href="https://github.com/weller0246/liferay-portal/commit/437a8c5b962d27f5048f2db64051f2cfc2556ce1">437a8c5b962d27f5048f2db64051f2cfc2556ce1</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2022/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2022/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/staging/usecase/Staging.testcase expected:&lt;...letWithoutContent";
     [java] [
     [java] ]    SystemSettings.ope...&gt; but was:&lt;...letWithoutContent";
     [java] []    SystemSettings.ope...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:435)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:281)
[stopwatch] [run.batch.test.action: 1:12.175 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-30/job/test-portal-source-format/2022//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220307064954829.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220307064954829.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1261241882.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null291422562
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 169ms
[junitreport] Deleting: /tmp/null291422562
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 03-07-2022 06:49:56:984 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</code></pre></details></html>

2022-03-07 14:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2022/">test-portal-source-format#2022</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2022/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/337">gaborlovasdotcom#337</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1628599923">[master] ci:test:sf - weller0246 &gt; gaborlovasdotcom - PR#337 - 2022-03-07[06:47:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/7171/">publish-testray-report#7171</a><br/></div></div>

2022-03-07 15:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1876/">test-portal-acceptance-pullrequest(master)#1876</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1876/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>staging<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/337">gaborlovasdotcom#337</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1628612390">[master] ci:test:staging - weller0246 &gt; gaborlovasdotcom - PR#337 - 2022-03-07[06:47:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/5356/">publish-testray-report#5356</a><br/></div></div>

2022-03-08 09:19 UTC, weller0246 commented
ci:test:sf

2022-03-08 09:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/5301/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5301/jenkins-report.html">here</a>.</b></p>

2022-03-08 09:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6b59cd0f086b56ef57502ab1a365e70d84eb5c73">6b59cd0f086b56ef57502ab1a365e70d84eb5c73</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/weller0246/liferay-portal/tree/LRQA-73647">LRQA-73647</a><br/>Branch GIT ID: <a href="https://github.com/weller0246/liferay-portal/commit/8af4599517c7f41f7a7bc95d341063b98b28b1c6">8af4599517c7f41f7a7bc95d341063b98b28b1c6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/5301/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5301/jenkins-report.html">here</a>.</h5></details></html>

2022-03-08 09:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/5301/">test-portal-source-format#5301</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5301/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/337">gaborlovasdotcom#337</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1629239795">[master] ci:test:sf - weller0246 &gt; gaborlovasdotcom - PR#337 - 2022-03-08[01:19:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/2314/">publish-testray-report#2314</a><br/></div></div>

2022-03-08 09:35 UTC, weller0246 commented
@gaborlovasdotcom please review my PR and forward it if you have the time!

2022-03-08 12:40 UTC, gaborlovasdotcom requested changes
Please clean up the commit, and it's good to go

2022-03-08 12:40 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/staging/usecase/Staging.testcase
> +		property portal.upstream = "marcell";
Please remove this line :).

2022-03-09 08:22 UTC, weller0246 commented
ci:forward

2022-03-09 08:22 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-03-09 08:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/617/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/617/jenkins-report.html">here</a>.</b></p>

2022-03-09 08:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/02bec99471ed706b691c92be479a34335a56614d">02bec99471ed706b691c92be479a34335a56614d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/weller0246/liferay-portal/tree/LRQA-73647">LRQA-73647</a><br/>Branch GIT ID: <a href="https://github.com/weller0246/liferay-portal/commit/89beb8371b7e5dc27845fd2a7fa0ecb97942a470">89beb8371b7e5dc27845fd2a7fa0ecb97942a470</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/617/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/617/jenkins-report.html">here</a>.</h5></details></html>

2022-03-09 08:26 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-35.liferay.com/job/test-portal-source-format/617//consoleFull)

2022-03-09 08:27 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/114366
[Console](https://test-1-35.liferay.com/job/test-portal-source-format/617//consoleFull)

2022-03-09 08:27 UTC, closed without merging

2022-03-09 08:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/938/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/938/jenkins-report.html">here</a>.</b></p>

2022-03-09 08:30 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/114366

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/938//consoleFull)

2022-03-09 08:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/617/">test-portal-source-format#617</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/617/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/337">gaborlovasdotcom#337</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1629903125">[master] ci:test:sf - weller0246 &gt; gaborlovasdotcom - PR#337 - 2022-03-09[00:22:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/2584/">publish-testray-report#2584</a><br/></div></div>

2022-03-09 08:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/938/">test-portal-acceptance-pullrequest(master)#938</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/938/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/337">gaborlovasdotcom#337</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1629903145">[master] ci:test:relevant - weller0246 &gt; gaborlovasdotcom - PR#337 - 2022-03-09[00:27:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/2585/">publish-testray-report#2585</a><br/></div></div>