LRQA-71055
gaborlovasdotcom/liferay-portal pull request #383
Opened 2022-05-05 17:26 UTC by alessandromalves

2022-05-05 17:26 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-05-05 17:28 UTC, alessandromalves commented
ci:test:sf

2022-05-05 17:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/2501/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2501/jenkins-report.html">here</a>.</b></p>

2022-05-05 17:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/176/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/176/jenkins-report.html">here</a>.</b></p>

2022-05-05 17:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cd6d88ca846652a3c8299ba4dfc2da15f0aa206e">cd6d88ca846652a3c8299ba4dfc2da15f0aa206e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LRQA-71055">LRQA-71055</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/468700717740523cac058015f6d090303b4b8a64">468700717740523cac058015f6d090303b4b8a64</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/2501/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2501/jenkins-report.html">here</a>.</h5></details></html>

2022-05-05 17:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cd6d88ca846652a3c8299ba4dfc2da15f0aa206e">cd6d88ca846652a3c8299ba4dfc2da15f0aa206e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LRQA-71055">LRQA-71055</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/468700717740523cac058015f6d090303b4b8a64">468700717740523cac058015f6d090303b4b8a64</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/176/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/176/jenkins-report.html">here</a>.</h5></details></html>

2022-05-05 17:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/2501/">test-portal-source-format#2501</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2501/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/383">gaborlovasdotcom#383</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1749253565">[master] ci:test:sf - alessandromalves &gt; gaborlovasdotcom - PR#383 - 2022-05-05[10:28:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/9291/">publish-testray-report#9291</a><br/></div></div>

2022-05-05 17:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/176/">test-portal-source-format#176</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/176/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/383">gaborlovasdotcom#383</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1749253618">[master] ci:test:sf - alessandromalves &gt; gaborlovasdotcom - PR#383 - 2022-05-05[10:28:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/639/">publish-testray-report#639</a><br/></div></div>

2022-05-06 07:14 UTC, weller0246 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/exportimport/ExportImport.testcase
> +	@description = "Verify if is possible edit an exported template."
typo error, please fix it

2022-05-06 07:29 UTC, weller0246 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/exportimport/ExportImport.testcase
> +	@description = "Verify if is possible export and import a DDL via Global."
Typo error, please fix it

2022-05-06 09:03 UTC, weller0246 requested changes
Please look through the descriptions, and fix the grammar issues (like if is possible, verify is possible, etc). 
Another point is that I don't think we need to delete the "use case" wording from the description as we use it in every test case. ( cc @gaborlovasdotcom  please add your opinion about this).
And one last thing: Please use periods to separate when describing which ticket the current test case is connecting to and then the description, like this: "This is a use case for LPS-32577. Add user inherited roles as SAML attribute statements."

2022-05-06 17:19 UTC, alessandromalves commented
ci:test:sf

2022-05-06 17:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/2916/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/2916/jenkins-report.html">here</a>.</b></p>

2022-05-06 17:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cd6d88ca846652a3c8299ba4dfc2da15f0aa206e">cd6d88ca846652a3c8299ba4dfc2da15f0aa206e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LRQA-71055">LRQA-71055</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/40f7938f0256a8b840308504c2405eb862084fe6">40f7938f0256a8b840308504c2405eb862084fe6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/2916/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/2916/jenkins-report.html">here</a>.</h5></details></html>

2022-05-06 17:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/2916/">test-portal-source-format#2916</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/2916/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/383">gaborlovasdotcom#383</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1759406597">[master] ci:test:sf - alessandromalves &gt; gaborlovasdotcom - PR#383 - 2022-05-06[10:19:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/10818/">publish-testray-report#10818</a><br/></div></div>

2022-05-09 08:07 UTC, gaborlovasdotcom approved these changes
LGTM

2022-05-09 08:07 UTC, gaborlovasdotcom commented
ci:forward

2022-05-09 08:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-05-09 08:07 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-05-09 08:07 UTC, gaborlovasdotcom commented
fyi: @JoyceWang08211

2022-05-09 08:08 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-15.liferay.com/job/forward-pullrequest/257//consoleFull)

2022-05-09 08:08 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/117102
[Console](https://test-1-15.liferay.com/job/forward-pullrequest/257//consoleFull)

2022-05-09 08:08 UTC, closed without merging