Lps 133093
gaborlovasdotcom/liferay-portal pull request #99
Opened 2021-06-25 08:57 UTC by weller0246

https://issues.liferay.com/browse/LPS-133093

2021-06-25 08:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-05 12:56 UTC, gaborlovasdotcom requested changes
Please

1. Split changes by 1 commit / file
2. Remove SAMLToolBox.macro, and add it's new macros into SAML.macro

2021-07-05 15:04 UTC, weller0246 commented
ci:help:

2021-07-05 15:04 UTC, liferay-continuous-integration commented
## Available CI commands:
#### ci:close
&nbsp;&nbsp;&nbsp;&nbsp;Close the pull request.
#### ci:forward
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request  and forward the pullrequest to `brianchandotcom` if the required test suites pass.
#### ci:merge[:force]
&nbsp;&nbsp;&nbsp;&nbsp;Merge in the changes from the subrepo. All tests must pass before this command will successfully run. Optionally use the force flag to bypass failed tests.
#### ci:reevaluate:[buildID]
&nbsp;&nbsp;&nbsp;&nbsp;Reevaluate the pull request result from a generated build ID.
#### ci:reopen
&nbsp;&nbsp;&nbsp;&nbsp;Reopen the pull request.
#### ci:stop[:suite]
&nbsp;&nbsp;&nbsp;&nbsp;Stop all currrently running tests. Optionally specify the name of the test suite.
#### ci:test[:suite][:SHA|nocompile|norebase]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request.Optionally specify the name of the test suite and/or optionally specify the upstream SHA to test against or use "nocompile" to test with a prebuilt bundle or use "norebase" to test without rebasing.

&nbsp;&nbsp;&nbsp;&nbsp;List of available test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance** - Test acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional** - Test acceptance functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-upstream** - Test acceptance upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**accounts** - Test Accounts tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud** - Test Analytics Cloud tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**auto-tagging** - Test Auto Tagging tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend** - Test backend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend-hypersonic** - Test backend tests on Hypersonic.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blade** - Test Blade samples tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blogs** - Test Blogs tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bulk-editing** - Test Bulk Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bundle** - Saves a compiled tomcat bundle.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**calendar** - Test Calendar tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**click-to-chat** - Test Click to Chat tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clustering** - Test clustering tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce** - Test only Commerce tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es7-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-functional** - Test only Commerce functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**content-page-review** - Test Content Page Review (comments) tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine** - Test Data Engine functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**depot** - Test Depot tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**digital-signature** - Test Digital Signature tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dl-store** - Test Document Library Store tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**documents** - Test Document and Media tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**drools** - Test Drools tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dummy** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo** - Test all Echo (WCM) team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-acceptance** - Test Echo (WCM) team acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-upgrade** - Test Echo (WCM) team upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**environments** - Test environment acceptance functional tests on all available environment stacks.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**export-import** - Test exportimport tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms** - Test forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-functional** - Test only functional forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend** - Test frontend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet** - Test upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet-bucket** - Test a subset of upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gradle-plugins** - Test Gradle Plugins tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless** - Test headless team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-acceptance** - Test headless team acceptance tests considering Headless and Rest Builder.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jdk11** - Test acceptance, smoke, and upgrade functional tests against JDK11.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jsf** - Test Liferay Faces tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**kaleo-forms** - Test Kaleo Forms admin tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**knowledge-base** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**ldap** - Test LDAP tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license** - Compile a release bundle and execute tests for licensing.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license-cluster** - Compile a release bundle and execute tests for cluster licensing on 32GB slaves.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**liferay-online** - Compile a release bundle and execute tests with liferay online properties.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima** - Test Lima tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lpkg** - Test LPKG tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**message-boards** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**mfa** - Test Multi Factor Authentication tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**oauth2** - Test OAuth 2 tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**onedrive** - Test OneDrive tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**online-editing** - Test Online Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**password-policies** - Test Password Policies tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**portal-release-upstream** - Run full release tests against a release bundle compiled from head.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**poshi** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**poshi-gauntlet** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**project-templates** - Test project-templates tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**publications** - Test publications tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**publications-environments** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**questions-acceptance** - Test headless team acceptance tests considering Questions.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**redirect** - Test Redirection tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant** - Test relevant changes only.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**reports** - Test Reports tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**roles** - Test Roles tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**saml** - Test SAML tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search** - Test search tests with the Elasticsearch 7 search engine.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search-remote** - Test only search tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search-remote-minimum** - Test search tests with the minimum compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**security** - Test security tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**seo** - Test SEO tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf** - Test source formatter.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sharepoint** - Test Sharepoint 2010 tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sharing** - Test Asset Sharing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**site-template** - Test Site Template tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**smoke** - Run smoke test with all available configurations in PortalSmoke.testcase
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**staging** - Test Staging components tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sybase** - Test functional and integration tests on Sybase database.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:* [...]

2021-07-05 15:04 UTC, weller0246 commented
ci:test:saml

2021-07-06 08:49 UTC, gaborlovasdotcom commented
ci:test:sf

2021-07-06 08:49 UTC, gaborlovasdotcom commented
ci:test:saml:nocompile

2021-07-06 08:49 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-06 08:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/5882/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-portal-source-format/builds/5882/jenkins-report.html">here</a>.</b></p>

2021-07-06 08:51 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f38f79ec048f97eaf7f4a17ea48673e4eaee99bf">f38f79ec048f97eaf7f4a17ea48673e4eaee99bf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/weller0246/liferay-portal/tree/LPS-133093">LPS-133093</a><br/>Branch GIT ID: <a href="https://github.com/weller0246/liferay-portal/commit/1fbb5109efcfdef4cef0a6904c728b8011e38cf5">1fbb5109efcfdef4cef0a6904c728b8011e38cf5</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5882/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5882/jenkins-report.html">here</a>.</h5><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/weller0246/liferay-portal/tree/LPS-133093">weller0246/LPS-133093</a></strong><pre><code>Target exception: java.lang.RuntimeException: Unable to rebase weller0246-99-LPS-133093 to master
error: Failed to merge in the changes.</code></pre></p></div></details></html>

2021-07-12 13:27 UTC, weller0246 commented
ci:test:saml:nocompile

2021-07-12 13:27 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-12 14:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>saml</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/2795/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2795/jenkins-report.html">here</a>.</b></p>

2021-07-12 16:35 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:saml - 6 out of 9 jobs passed in 2 hours 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f04ab1731b97a88ca360afa8883efc514a1f2e4e">f04ab1731b97a88ca360afa8883efc514a1f2e4e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f04ab1731b97a88ca360afa8883efc514a1f2e4e">f04ab1731b97a88ca360afa8883efc514a1f2e4e</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2094">Acceptance Upstream DXP (master) #2094</a></p><details><summary><strong>ci:test:saml - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/2795/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/466575/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473449/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19916/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/466572/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19914/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19917/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19915/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1378/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2795/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/466575/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>16 Tests Failed.</p></div><ol><li><div><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/466575//consoleText">AXIS_VARIABLE=11,label_exp=!master #466575</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-110-35] which is computer hudson.slaves.SlaveComputer@59605842 and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute Scripts' marked build as failure
Finished: FAILURE</code></pre></div></li><li><div><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/466575//consoleText">AXIS_VARIABLE=12,label_exp=!master #466575</a><pre><code>	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=${NODE_NAME}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-110-44] which is computer hudson.slaves.SlaveComputer@2977a79b and has channel null
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:186)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:96)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:84)
	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
	 [...]

2021-07-12 16:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/2795/">test-portal-acceptance-pullrequest(master)#2795</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2795/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>saml<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/gaborlovasdotcom/liferay-portal/pull/99">gaborlovasdotcom#99</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1546578952">[master] ci:test:saml - weller0246 &gt; gaborlovasdotcom - PR#99 - 2021-07-12[06:55:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7790/">publish-testray-report#7790</a><br/></div></div>

2021-07-13 10:48 UTC, gaborlovasdotcom commented
ci:test:saml:nocompile

2021-07-13 10:48 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-13 17:46 UTC, gaborlovasdotcom requested changes
@weller0246 I finished the review, please see my comments.
cc @ferenconodiD

2021-07-13 17:46 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +			index = "0",
As I remember, this needs some clever naming to reflect the business logic we set in our tests.

2021-07-13 17:46 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +	test deleteUserAfterSAMLSetupAndVerify {
All test names must start with a capital letter.

2021-07-14 07:51 UTC, gaborlovasdotcom commented
ci:test:saml:nocompile

2021-07-14 07:51 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle..

2021-07-14 10:50 UTC, weller0246 commented on portal-web/test/functional/com/liferay/portalweb/macros/User.macro
> +			MenuItem.clickNoError(menuItem = "Deactivate");
I found a message from last year, that User#deactivateCP and User#deleteCP macros are used in the tests so this change can be discarded and I'll refactor with these methods  
https://liferay.slack.com/archives/CD7939WBE/p1580321226011700?thread_ts=1580299195.010400&cid=CD7939WBE

2021-07-14 11:39 UTC, gaborlovasdotcom commented
ci:stop

2021-07-14 11:40 UTC, gaborlovasdotcom commented
@weller0246 Please create a new PR when changes are applied, thanks.

2021-07-14 11:40 UTC, closed without merging